acconut/urls.py
from django.urls import path
from . import views

app_name="acconut"
urlpatterns = [
    path("profile/<int:pk>", views.ProfileDetailView.as_view(), name="profile"),
    path("register_user/",views.register_user, name="register_user"),
    path("login_user/",views.login_user, name="login"),


]

computer/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include(("post.urls","post"),namespace="post")),
    path("members/",include(("acconut.urls","acconut"),namespace="acconut")),
    path("members/",include("django.contrib.auth.urls")),
    path("accounts/",include("django.contrib.auth.urls"))

]
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATICFILES_DIRS)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from .views import postlistview,PostDetailView,CategoryListView,categorydetailview,create_post,PostUpdateView,PostDeleteViwe
from django.conf import settings
from django.conf.urls.static import static
app_name="post"
urlpatterns = [
    path("", postlistview, name="postlist"),
    path("post_detail/<slug:slug_f>/<int:pk>", PostDetailView.as_view(), name="postdetail"),
    path("update/<slug:slug_f>/<int:pk>", PostUpdateView.as_view(), name="update"),
    path("delete/<slug:slug_f>/<int:pk>", PostDeleteViwe.as_view(), name="delete"),
    path("category/", CategoryListView.as_view(), name="category"),
    path("category_detail/<int:i_id>", categorydetailview, name="categorydetail"),
    path("createpost/",create_post, name="create_post"),

]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

acconut/models.py
from django.db import models

# Create your models here.

post/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from  django.core.files.uploadedfile import SimpleUploadedFile
from django.urls import reverse

class Category(models.Model):
    img=models.ImageField(upload_to="category")
    title=models.CharField(max_length=255)
    publish=models.DateTimeField(default=timezone.now)   

    
    def __str__ (self):
        return self.title
    
class Post (models.Model):
    title=models.CharField(max_length=300)
    price=models.PositiveIntegerField()
    category=models.ForeignKey(Category, on_delete=models.CASCADE)
    img=models.ImageField(upload_to="post")
    # img=models.FileField(blank=True,upload_to="post")
    # cove=SimpleUploadedFile(img,b"post/")
    model_post=models.CharField(max_length=300)
    cpu=models.CharField(max_length=300)
    ram=models.CharField(max_length=300)
    hard=models.CharField(max_length=300)
    gpu=models.CharField(max_length=300,default="...")
    description=models.TextField()
    created=models.DateTimeField(auto_now_add=True)
    slug=models.SlugField(max_length=250,unique_for_date="publish")
    author=models.ForeignKey(User,on_delete=models.CASCADE)
    update=models.DateTimeField(auto_now=True)
    publish=models.DateTimeField(default=timezone.now)
    
    
     
    def __str__ (self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("post:postdetail",args=[self.slug,self.id ])
        


class ImagSlid(models.Model):
    img=models.ImageField(upload_to="slid")
    publish=models.DateTimeField(default=timezone.now)
   
    

acconut/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class RegisterUserForm(UserCreationForm):
    email=forms.EmailField(widget=forms.EmailInput(attrs={"class" : "form-control"}))
    first_name=forms.CharField(max_length=80,widget=forms.TextInput(attrs={"class" : "form-control"}))
    last_name=forms.CharField(max_length=80,widget=forms.TextInput(attrs={"class" : "form-control"}))


    class Meta:
        model=User
        fields=("username","first_name","last_name","email","password1","password2")
    def __init__(self,*args, **kwargs):
        super(RegisterUserForm, self).__init__(*args, **kwargs)
        self.fields["username"].widget.attrs['class']="form-control"
        self.fields["password1"].widget.attrs['class']="form-control"
        self.fields["password2"].widget.attrs['class']="form-control"

post/forms.py
from django import forms
from .models import Post




class PostForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=["title",'img',"model_post","price","category","cpu","ram", "hard", "gpu","description", "slug"]
        labels={
            'img': "عکس",
            "model_post" : "مدل",
            "price": "قیمت",
            "category":"دسته",
            "description":"توضیحات",
             "slug":"slug",
        }

acconut/views.py
from django.shortcuts import render,redirect
from django.views.generic import CreateView,DetailView
from django.contrib.auth import authenticate,login
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin as LRM
from .forms import RegisterUserForm
from django.urls import reverse_lazy
from django.contrib.auth.models import User




class  ProfileDetailView(LRM,DetailView):
    model = User
    template_name = "acconut/profile.html"
    context_object_name="user"





def login_user(request):
    if request.method== "POST":
        username=request.POST["username"]
        password=request.POST["password"]
        user=authenticate(request,username=username,password=password)
        if user is not None :
            login(request, user)
            return redirect("post:postlist")
        else:
            messages.success(request, ("try again ..."))
            return redirect("acconut:login")
    else:
        return render(request,'acconut/authentication/login.html',{} )






def register_user(request):
    if request.method == "POST":
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            form.save()
            username= form.cleaned_data['username']
            password= form.cleaned_data['password1']
            user=authenticate(username=username,password=password)
            login(request,user)
            messages.success(request,("reqistration successful"))
            return redirect("post:postlist")
    else:
        form = RegisterUserForm()

    return render(request,"acconut/authentication/user_register.html",{"form":form})

post/views.py
from django.shortcuts import render,redirect
from django.views.generic import ListView,DetailView
from .models import Post,Category,ImagSlid
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin as LRM
from django.urls import reverse_lazy
from .forms import PostForm
from django.core.paginator import Paginator



class CategoryListView(ListView):
    model = Category
    paginate_by=3
    template_name = "post/categorylist.html"
    context_object_name="category_list"




def postlistview(request):
    Imgs=ImagSlid.objects.all()
    p=Paginator(Post.objects.all(),6)
    page=request.GET.get("page")
    pages=p.get_page(page)
    return render(request,"post/postlist.html",{"Imgs":Imgs,"pages":pages})
    



class PostDetailView(DetailView):
    model = Post
    template_name = "post/postdetail.html"
    context_object_name="postd_detail"

class PostUpdateView(LRM,UpdateView):
    model =Post
    template_name = "post/update.html"
    fields=["title",'img',"model_post","price","category","cpu","ram", "hard", "gpu","description"]
    

class PostDeleteViwe(LRM,DeleteView):
     model =Post
     template_name = "post/deletepost.html"
     success_url=reverse_lazy("post:postlist")






def categorydetailview(request,i_id):
    p=Paginator(Post.objects.filter(category=i_id),6)
    page=request.GET.get("page")
    pages=p.get_page(page)
    return render(request,'post/categorydetail.html',{"pages":pages})



@login_required
def create_post(request,pk=None):
    if request.method == "POST":
        form=PostForm(request.POST,request.FILES)
        if form.is_valid():
            form.instance.author = request.user
            form.save()
            return redirect("post:postlist")
    else:
        form=PostForm()
    return render(request,"acconut/createpost.html",{"form" :form})

templates/acconut/authentication/login.html
{% extends 'baes.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <div class="modal-body p-5 pt-0">
        <form class="">
          <div class="form-floating mb-3">
            <input type="text" class="form-control rounded-3" name="username"  placeholder="username">
            <label for="floatingInput">Email address</label>
          </div>
          <div class="form-floating mb-3">
            <input type="password" class="form-control rounded-3" name="password" placeholder="Password">
            <label for="floatingPassword">Password</label>
          </div>
          <button class="w-100 mb-2 btn btn-lg rounded-3 btn-primary" type="submit">Login</button>
         
        </div>
    


</form>    

{% endblock content %}

templates/acconut/authentication/user_register.html
{% extends 'baes.html' %}

{% block content %}

{% if form.errors %}

    <p>form is error</p>

{% endif %}

<div class="shadow p-4 mb-5 bg-body rounded">
    <form method="post"   action="{% url 'acconut:register_user' %}" >
        {% csrf_token %}
        {{form.as_p}}
        <input class="w-100 mb-2 btn btn-lg rounded-3 btn-primary" type="submit" value="Signup">
    </form>



</div>

{% endblock content %}

templates/acconut/createpost.html
{% extends 'baes.html' %}

{% block content %}
   <form enctype="multipart/form-data" method="post" >
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="create">
   </form>
{% endblock content %}

templates/acconut/profile.html
{% extends 'baes.html' %}

{% block content %}

    <div class="card mb-4">
      <div class="card-body">
        <div class="row">
          <div class="col-sm-3">
            <p class="mb-0">First Name</p>
          </div>
          <div class="col-sm-9">
            <p class="text-muted mb-0">{{user.first_name}}</p>
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm-3">
            <p class="mb-0">Last Name</p>
          </div>
          <div class="col-sm-9">
            <p class="text-muted mb-0">{{user.last_name}}</p>
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm-3">
            <p class="mb-0">Email</p>
          </div>
          <div class="col-sm-9">
            <p class="text-muted mb-0">{{user.email}}</p>
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm-3">
            <p class="mb-0">UserName</p>
          </div>
          <div class="col-sm-9">
            <p class="text-muted mb-0">{{user.username}}</p>
          </div>
        </div>
        <hr>
      </div>
    </div>
    

    
    <a href="{% url 'password_change' %}"><button type="button" class="btn btn-primary">Reset Password</button></a>
    <a href="{% url 'password_reset'%}"><button style="margin-right: 10px;" type="button" class="btn btn-outline-success">Password Reset</button></a>
{% endblock content %}

templates/baes.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.png' %}"/>
    <title>{% block title %}{% endblock title %}</title>
    {% block head %}{% endblock head %}
</head>
<body >

    {% include "static/header.html" %}
    {% block content %}{% endblock content %}
    {% include "static/footer.html" %}
  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    
  
</body>
</html>

templates/pagin.html
<br>
<br>
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    <li class="page-item ">
    {% if pages.has_previous  %}
    <li class="page-item"> <a class="page-link" href="?page=1">first</a></li>
      <li class="page-item">  <a class="page-link" href="?page={{pages.previous_page_number}}">previous</a></li>
    {% endif %}
    <li class="page-item"><a class="page-link" href="#">page {{pages.number}} of {{pages.paginator.num_pages}}</a></li>
      

    {% if pages.has_next %}
    <li class="page-item"><a  class="page-link"  href="?page={{pages.next_page_number}}">Next</a></li>
      <li class="page-item"><a class="page-link" href="?page={{pages.paginator.num_pages}}">last</a></li>
    {% endif %}
    </li>
  </ul>
</nav>

templates/post/categorydetail.html
{% extends 'baes.html' %}

{% block content %}


<div class="row row-cols-1 row-cols-md-3 g-4" >
{% for post  in pages  %}
  
<div class="col" style="paddght: -10px;padding-right: ;padding-left: 50px; margin-top: 45px; ">
  <div class="card  " style="width: 18rem;">
  <a href="{% url 'post:postdetail' post.slug  post.id %}">
    <img src="{{post.img.url}}" class="card-img-top" alt="...">
    <div class="card-body">
      <h3>{{post.title}}</h3>
      <p class="card-text">{{post.price}}</p>
    </div>
  </a>
</div>
</div>
{% endfor %}  

</div>


{% include "pagin.html" %}



{% endblock content %}

templates/post/categorylist.html
{% extends 'baes.html' %}

{% block content %}
<div class="row row-cols-1 row-cols-md-3 g-4">
{% for category  in category_list %}
<div class="col" style="paddght: -10px;padding-right: ;padding-left: 50px; margin-top: 45px; ">
  <div class="card  " style="width: 18rem;">
    <a href="{% url 'post:categorydetail' category.id %}">
      <img src="{{category.img.url}}" class="card-img-top" alt="...">
      <div class="card-body">
        <h3>{{category.title}}</h3>
      </div>
    </a>
  
  </div>
</div>
{% endfor %}  
</div>

<br>
<br>
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    <li class="page-item ">
    {% if page_obj.has_previous  %}
    <li class="page-item"> <a class="page-link" href="?page=1">first</a></li>
      <li class="page-item">  <a class="page-link" href="?page={{page_obj.previous_page_number}}">previous</a></li>
    {% endif %}
    <li class="page-item"><a class="page-link" href="#">page {{page_obj.number}} of {{page_obj.paginator.num_page_obj}}</a></li>
      

    {% if page_obj.has_next %}
    <li class="page-item"><a  class="page-link"  href="?page={{page_obj.next_page_number}}">Next</a></li>
      <li class="page-item"><a class="page-link" href="?page={{page_obj.paginator.num_pages}}">last</a></li>
    {% endif %}
    </li>
  </ul>
</nav>




{% endblock content %}

templates/post/deletepost.html
{% extends 'baes.html' %}

{% block content %}
    <h1>Are you sure you want to delete this post ? </h1>
   <form enctype="multipart/form-data" method="post" >
        {% csrf_token %}
        <input class="btn btn-primary" type="submit" value="Yes">
        <a href="{% url 'post:postlist' %}">
        <input class="btn btn-primary" type="submit" value="No">
        </a>
    
   </form>
{% endblock content %}

templates/post/postdetail.html
{% extends 'baes.html' %}

{% block content %}
    <div class="modal-body p-5 pt-0">
    <div class="modal-content rounded-4 shadow">
    <p class="w-100 py-2 mb-2 btn " >{{postd_detail.title}}</p>
    <img  class="rounded mx-auto d-block"  style="width:450px "    src="{{postd_detail.img.url}}" alt="">
    <p class="w-100 py-2 mb-2 btn " >Price : {{postd_detail.price}} T </p>
    <p class="w-100 py-2 mb-2 btn " >Model : {{postd_detail.model_post}}</p>
    <p class="w-100 py-2 mb-2 btn " >Cpu  : {{postd_detail.cpu}}</p>
    <p class="w-100 py-2 mb-2 btn " >Ram  : {{postd_detail.ram}}</p>
    <p class="w-100 py-2 mb-2 btn " >Hard : {{postd_detail.hard}}</p>
    <p class="w-100 py-2 mb-2 btn " >Gpu : {{postd_detail.gpu}} </p>
    <p class="w-100 py-2 mb-2 btn " >Description : {{postd_detail.description}}</p>
    <p class="w-100 py-2 mb-2 btn ">Author : {{postd_detail.author}}</p>
    </div>
</div>
{% if request.user.is_authenticated %}
    <a  href="{% url 'post:update' postd_detail.slug postd_detail.id %}"><button class="w-100 mb-2 btn btn-lg rounded-3 btn-primary" type="submit">Edit</button></a>
    <a  href="{% url 'post:delete' postd_detail.slug postd_detail.id %}"><button class="w-100 mb-2 btn btn-lg rounded-3 btn-primary" type="submit">Delete</button></a>
{% endif %}
{% endblock content %}

templates/post/postlist.html
{% extends 'baes.html' %}
{% load static %}

{% block content %}

{% include "static/slider.html" %}
  







<div class="row row-cols-1 row-cols-md-3 g-4" >

{% for post  in pages %}


<div class="col  " style="paddght: -10px;padding-right: ;padding-left: 50px; margin-top: 45px;    ">
<div class="card  " style="width: 18rem;">
  <a href="{% url 'post:postdetail' post.slug  post.id %}">
    <img src="{{post.img.url}}" class="card-img-top" alt="...">
    <div class="card-body">
      <h3>{{post.title}}</h3>
      <p class="card-text">Price : {{post.price}} T </p>
    </div>
  </a>


</div>
</div>
{% endfor %}  

</div>
<br>
<br>

{% include "pagin.html" %}




{% if request.user.is_authenticated %}

<a class="nav-link" href="{% url 'post:create_post' %}" style="margin: -89px 110px 0px; float: right;"><button type="button" class="btn btn-success">New Post</button></a>


{% endif %}
{% endblock content %}

templates/post/update.html
{% extends 'baes.html' %}

{% block content %}
   <form enctype="multipart/form-data" method="post" >
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="create">
   </form>
{% endblock content %}